name: Pylint

on: [push]

jobs:
  build:    
    strategy:
      fail-fast: false
      matrix:
        os: [macOs-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: prefix-dev/setup-pixi@v0.8.0
      with:
        pixi-version: v0.39.0
        cache: false
    - run: pixi run lint
    - run: pixi run test
